# Generated by Django 3.1.7 on 2021-05-23 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210523_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 17, 12, 51, 896098)),
        ),
    ]
