# Generated by Django 3.1.7 on 2021-05-23 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210523_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 17, 41, 39, 162644)),
        ),
    ]
