# Generated by Django 3.1.7 on 2021-05-27 15:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_auto_20210523_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 19, 1, 49, 781449)),
        ),
        migrations.CreateModel(
            name='Verificateuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificated', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 27, 19, 1, 49, 781449))),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_v', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
