# Generated by Django 3.1.7 on 2021-05-27 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210527_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 20, 4, 49, 516985)),
        ),
        migrations.AlterField(
            model_name='verificateuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 20, 4, 49, 521986)),
        ),
    ]
