# Generated by Django 3.1.7 on 2021-05-27 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210527_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 22, 11, 24, 903357)),
        ),
        migrations.AlterField(
            model_name='verificateuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 22, 11, 24, 903357)),
        ),
    ]
