# Generated by Django 3.1.7 on 2021-05-28 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20210528_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 16, 37, 51, 643108)),
        ),
        migrations.AlterField(
            model_name='verificateuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 16, 37, 51, 658708)),
        ),
    ]
